namespace: caweb
name: caweb
image:
  repository: wlanboy/caweb
  tag: latest
service:
  port: 2000
pvc:
  name: caweb-data-pvc
  size: 10Mi
  mountPath: /data

certmanager:
  enabled: true
  issuer: local-ca-issuer
  kind: ClusterIssuer
  secretName: caweb-tls
  