namespace: caweb
name: caweb
image:
  repository: wlanboy/caweb
  tag: latest
  pullPolicy: Always
service:
  port: 2000
pvc:
  name: caweb-data-pvc
  size: 10Mi
  mountPath: /data
  storageClassName: "local-path"

gatewayNamespace: istio-ingress

hosts: 
  - caweb.tp.lan
  - caweb.gmk.lan

certmanager:
  enabled: true
  issuer: local-ca-issuer
  kind: ClusterIssuer
  secretName: caweb-tls
